#!/usr/bin/env bash
# Persistent RunPod boot bring-up for Pastor-AI (lives on network volume).
# Safe to re-run; starts stack once GPU/network are ready.
#
# REQUIRED for migrate / new pod: set Pod "Container Start Command" to:
#   bash -lc 'nohup bash /workspace/pastor-ai/onboot.sh >>/workspace/pastor-ai/logs/onboot.log 2>&1 & exec /start.sh'
set -euo pipefail

WS="${WORKSPACE_ROOT:-/workspace/pastor-ai}"
LOG_DIR="$WS/logs"
LOCK="$LOG_DIR/onboot.lock"
mkdir -p "$LOG_DIR" "$WS/.cloudflared"

exec >>"$LOG_DIR/onboot.log" 2>&1
echo ""
echo "========== onboot $(date -Is) pid=$$ =========="

# Single-flight lock (ignore stale locks older than 2h)
if [[ -f "$LOCK" ]]; then
  lock_age=$(( $(date +%s) - $(stat -c %Y "$LOCK" 2>/dev/null || echo 0) ))
  if [[ "$lock_age" -lt 7200 ]] && kill -0 "$(cat "$LOCK" 2>/dev/null || echo 0)" 2>/dev/null; then
    echo "Another onboot is running; exiting."
    exit 0
  fi
fi
echo $$ >"$LOCK"
trap 'rm -f "$LOCK"' EXIT

install_boot_hooks() {
  cat >/pre_start.sh <<'HOOK'
#!/usr/bin/env bash
# Generated by /workspace/pastor-ai/onboot.sh — launches Pastor-AI after pod boot.
nohup bash /workspace/pastor-ai/onboot.sh >>/workspace/pastor-ai/logs/onboot.log 2>&1 &
HOOK
  chmod +x /pre_start.sh

  if [[ -f /start.sh ]] && ! grep -q 'pastor-ai/onboot.sh' /start.sh; then
    if grep -q 'sleep infinity' /start.sh; then
      sed -i '/sleep infinity/i\
# Pastor-AI auto-start (volume-backed)\
if [[ -x /workspace/pastor-ai/onboot.sh ]]; then\
  nohup bash /workspace/pastor-ai/onboot.sh >>/workspace/pastor-ai/logs/onboot.log 2>&1 &\
fi\
' /start.sh
    else
      cat >>/start.sh <<'HOOK'

# Pastor-AI auto-start (volume-backed)
if [[ -x /workspace/pastor-ai/onboot.sh ]]; then
  nohup bash /workspace/pastor-ai/onboot.sh >>/workspace/pastor-ai/logs/onboot.log 2>&1 &
fi
HOOK
    fi
    echo "Patched /start.sh with onboot hook"
  else
    echo "Boot hooks already present or /start.sh missing"
  fi

  # Reminder file for operators (volume-backed)
  cat >"$WS/runpod-docker-command.txt" <<'CMD'
# Paste this as the RunPod Pod "Container Start Command" / Docker Command
# (Pod Settings → Edit → Container Start Command) so Pastor-AI always boots
# even after a full container recreate / network-volume migrate to a new pod.
#
# Keeps the stock RunPod /start.sh (SSH, Jupyter, nginx) AND launches onboot.

bash -lc 'nohup bash /workspace/pastor-ai/onboot.sh >>/workspace/pastor-ai/logs/onboot.log 2>&1 & exec /start.sh'
CMD
}

ensure_cloudflared_bin() {
  if command -v cloudflared >/dev/null 2>&1; then
    return 0
  fi
  echo "Installing cloudflared..."
  curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
    -o /usr/local/bin/cloudflared
  chmod +x /usr/local/bin/cloudflared
}

# Start named tunnel ASAP so Cloudflare stops returning 1033 while the rest boots.
ensure_named_tunnel() {
  local token_file="${CLOUDFLARE_TUNNEL_TOKEN_FILE:-$WS/.cloudflared/tunnel.token}"
  [[ -f "$token_file" ]] || { echo "No Cloudflare tunnel token at $token_file"; return 0; }
  ensure_cloudflared_bin
  if pgrep -f 'cloudflared tunnel' >/dev/null 2>&1; then
    echo "cloudflared already running"
    return 0
  fi
  echo "Starting Cloudflare named tunnel early..."
  : >"$LOG_DIR/cloudflared.log"
  screen -dmS cloudflared bash -lc \
    "cloudflared tunnel --no-autoupdate run --token \"\$(cat '$token_file')\" >>'$LOG_DIR/cloudflared.log' 2>&1"
  sleep 2
  if pgrep -f 'cloudflared tunnel' >/dev/null 2>&1; then
    echo "cloudflared up (clears Cloudflare 1033 once connected)"
  else
    echo "WARNING: cloudflared failed to start — see $LOG_DIR/cloudflared.log"
    tail -20 "$LOG_DIR/cloudflared.log" || true
  fi
}

install_boot_hooks

for i in $(seq 1 60); do
  [[ -d "$WS" && -f "$WS/start.sh" ]] && break
  sleep 2
done
[[ -f "$WS/start.sh" ]] || { echo "Missing $WS/start.sh"; exit 1; }

for i in $(seq 1 90); do
  if [[ -e /dev/nvidia0 ]] || command -v nvidia-smi >/dev/null 2>&1; then
    nvidia-smi >/dev/null 2>&1 && break
  fi
  sleep 2
done

export DEBIAN_FRONTEND=noninteractive
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-/workspace/.cache/pip}"
export TMPDIR="${TMPDIR:-/workspace/tmp}"
mkdir -p "$PIP_CACHE_DIR" "$TMPDIR"

need_apt=0
command -v screen >/dev/null 2>&1 || need_apt=1
command -v curl >/dev/null 2>&1 || need_apt=1
command -v psql >/dev/null 2>&1 || need_apt=1
if [[ "$need_apt" -eq 1 ]]; then
  echo "Installing apt deps (screen/curl/postgresql)..."
  apt-get update -qq
  apt-get install -y -qq screen curl ca-certificates postgresql postgresql-contrib >/dev/null
fi

ensure_cloudflared_bin

if [[ -f "$WS/.cloudflared/tunnel.token" ]]; then
  if grep -q '^TUNNEL=' "$WS/config.env" 2>/dev/null; then
    sed -i 's/^TUNNEL=.*/TUNNEL=cloudflared/' "$WS/config.env"
  else
    echo 'TUNNEL=cloudflared' >>"$WS/config.env"
  fi
fi

# Clear Cloudflare 1033 as early as possible
ensure_named_tunnel

# Free stale Django/gunicorn from prior half-boots
fuser -k 8000/tcp 2>/dev/null || true
pkill -9 -f 'gunicorn pastor_ai' 2>/dev/null || true

if curl -sf --max-time 3 http://127.0.0.1:8000/ >/dev/null \
   && curl -sf --max-time 3 http://127.0.0.1:8010/v1/models >/dev/null \
   && curl -sf --max-time 3 http://127.0.0.1:6333/ >/dev/null; then
  echo "Stack already healthy; tunnel ensured."
  ensure_named_tunnel
  echo "onboot done (already up) at $(date -Is)"
  exit 0
fi

echo "Starting Pastor-AI stack via start.sh..."
bash "$WS/start.sh"
ensure_named_tunnel

# Confirm Django finished migrate (start.sh launches it in screen)
for i in $(seq 1 60); do
  if curl -sf --max-time 3 http://127.0.0.1:8000/ >/dev/null; then
    echo "Django healthy after onboot"
    break
  fi
  sleep 2
done
if ! curl -sf --max-time 3 http://127.0.0.1:8000/ >/dev/null; then
  echo "WARNING: Django still not up — see $LOG_DIR/django.log"
  tail -40 "$LOG_DIR/django.log" || true
fi

echo "onboot finished at $(date -Is)"
