# Generated by Django 5.2.12 on 2026-04-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_name", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("original_extension", models.CharField(max_length=10)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestedChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_hash", models.CharField(max_length=64, unique=True)),
                ("qdrant_point_id", models.CharField(max_length=36, unique=True)),
                ("source_name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="core.ingesteddocument"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ingestedchunk",
            index=models.Index(fields=["source_name"], name="core_ingest_source__54860e_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestedchunk",
            index=models.Index(fields=["created_at"], name="core_ingest_created_926434_idx"),
        ),
    ]
