# Generated by Django 5.2.12 on 2026-04-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ingestion_tracking_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_by", models.CharField(max_length=150)),
                ("replace_existing_sources", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("files_received", models.PositiveIntegerField(default=0)),
                ("files_processed", models.PositiveIntegerField(default=0)),
                ("files_skipped_as_duplicates", models.PositiveIntegerField(default=0)),
                ("chunks_created", models.PositiveIntegerField(default=0)),
                ("chunks_skipped_as_duplicates", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="IngestionJobLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="core.ingestionjob"),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
