# Generated by Django 5.2.12 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ingesteddocument_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="files_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="IngestionJobFileFailure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_name", models.CharField(max_length=512)),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_failures",
                        to="core.ingestionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestionjobfilefailure",
            index=models.Index(fields=["job", "created_at"], name="core_ingest_job_id_2c4137_idx"),
        ),
    ]

