# Generated by Django 4.2.30 on 2026-08-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_responsereport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='responsereport',
            new_name='core_respon_status_388563_idx',
            old_name='core_respon_status_6f0c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='responsereport',
            new_name='core_respon_session_e4e085_idx',
            old_name='core_respon_session_0c5e91_idx',
        ),
    ]
