# Generated by Django 4.2.30 on 2026-08-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_responsereport_index_names'),
        ('core', '0010_video_ingestion'),
    ]

    operations = [
    ]
