"""
Django settings for pastor_ai project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

if not DEBUG and SECRET_KEY in {"", "dev-only-change-me"}:
    raise ValueError("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

IS_PRODUCTION = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
    'api.apps.ApiConfig',
    'pastor_ai',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pastor_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pastor_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Postgres when POSTGRES_HOST is set (docker/production); otherwise SQLite for local/dev/tests.
_use_sqlite = os.getenv("DJANGO_USE_SQLITE", "").lower() in ("1", "true", "yes") or not os.getenv(
    "POSTGRES_HOST"
)
if _use_sqlite:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "ai_db"),
            "USER": os.getenv("POSTGRES_USER", "admin"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

FRONTEND_BUILD_DIR = os.getenv("FRONTEND_BUILD_DIR", "/frontend")

# Admin ingestion can POST many files at once; Django's default caps raise TooManyFilesSent /
# TooManyFieldsSent on large multi-file batches.
DATA_UPLOAD_MAX_NUMBER_FILES = int(os.getenv("DATA_UPLOAD_MAX_NUMBER_FILES", "10000"))
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.getenv("DATA_UPLOAD_MAX_NUMBER_FIELDS", "20000"))
# Video ingestion uploads can be hundreds of MB; keep file bodies on disk.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(2 * 1024 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = os.getenv("DJANGO_CORS_ALLOW_ALL_ORIGINS", "false").lower() == "true"
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "http://localhost").split(",")
    if origin.strip()
]

# Required when running Django behind Nginx TLS termination.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django security hardening defaults for public deployment.
# Default off so local/dev/tests work over HTTP; enable explicitly in production compose.
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "false").lower() == "true"
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", str(IS_PRODUCTION)).lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", str(IS_PRODUCTION)).lower() == "true"
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", str(IS_PRODUCTION)).lower() == "true"
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "false").lower() == "true"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
REFERRER_POLICY = os.getenv("DJANGO_REFERRER_POLICY", "strict-origin-when-cross-origin")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # TokenAuthentication lives in rest_framework.authentication (not
        # rest_framework.authtoken.authentication — that module does not exist).
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("DRF_THROTTLE_ANON", "30/minute"),
        "user": os.getenv("DRF_THROTTLE_USER", "120/minute"),
    },
}

# Google Sign-In popups need to hand control back to this window. Django's
# default COOP ("same-origin") blocks that and can leave GIS stuck on
# accounts.google.com/gsi/transform after account selection.
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


def _load_dotenv_value(key: str) -> str:
    env_path = BASE_DIR / ".env"
    if not env_path.is_file():
        return ""
    try:
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            if k.strip() == key:
                return v.strip().strip("'").strip('"')
    except OSError:
        return ""
    return ""


# Google Sign-In (Flutter posts a Google ID token to /api/auth/google/).
# Must match the OAuth 2.0 Web client ID used when building the Flutter web app.
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "") or _load_dotenv_value("GOOGLE_CLIENT_ID")

# Stripe Premium subscriptions (Embedded Checkout).
# Paste keys into tokens.env / config.env — never commit live secrets.
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "") or _load_dotenv_value("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = (
    os.environ.get("STRIPE_PUBLISHABLE_KEY", "") or _load_dotenv_value("STRIPE_PUBLISHABLE_KEY")
)
STRIPE_WEBHOOK_SECRET = (
    os.environ.get("STRIPE_WEBHOOK_SECRET", "") or _load_dotenv_value("STRIPE_WEBHOOK_SECRET")
)
STRIPE_PRICE_MONTHLY = (
    os.environ.get("STRIPE_PRICE_MONTHLY", "") or _load_dotenv_value("STRIPE_PRICE_MONTHLY")
)
STRIPE_PRICE_YEARLY = (
    os.environ.get("STRIPE_PRICE_YEARLY", "") or _load_dotenv_value("STRIPE_PRICE_YEARLY")
)
# Used for Checkout return_url. Example: https://your-tunnel-or-domain
PUBLIC_APP_URL = os.environ.get("PUBLIC_APP_URL", "") or _load_dotenv_value("PUBLIC_APP_URL")

# TEMPORARY: gift Premium via fake checkout UI until Stripe keys are available.
# Auto-enables when Stripe is not configured. Set to false once Stripe is live.
_billing_mock_raw = os.environ.get("BILLING_MOCK_CHECKOUT", "") or _load_dotenv_value(
    "BILLING_MOCK_CHECKOUT"
)
BILLING_MOCK_CHECKOUT = _billing_mock_raw.strip().lower()

# Vimeo Folder sync for Daily Devotionals media library.
# Folder URL example: https://vimeo.com/user/21759939/folder/24205069
VIMEO_ACCESS_TOKEN = os.environ.get("VIMEO_ACCESS_TOKEN", "") or _load_dotenv_value("VIMEO_ACCESS_TOKEN")
VIMEO_FOLDER_ID = os.environ.get("VIMEO_FOLDER_ID", "") or _load_dotenv_value("VIMEO_FOLDER_ID")
VIMEO_USER_ID = os.environ.get("VIMEO_USER_ID", "") or _load_dotenv_value("VIMEO_USER_ID")
# Deprecated alias — still read if VIMEO_FOLDER_ID is empty.
VIMEO_SHOWCASE_ID = os.environ.get("VIMEO_SHOWCASE_ID", "") or _load_dotenv_value("VIMEO_SHOWCASE_ID")
VIMEO_FREE_PREVIEW_ID = (
    os.environ.get("VIMEO_FREE_PREVIEW_ID", "") or _load_dotenv_value("VIMEO_FREE_PREVIEW_ID")
)

